{
  "model_params": {
    "tabnet": {
      "n_d": 64,
      "n_a": 64,
      "n_steps": 5,
      "gamma": 1.5,
      "n_independent": 2,
      "n_shared": 2,
      "virtual_batch_size": 256,
      "momentum": 0.02,
      "mask_type": "sparsemax"
    },
    "gnn": {
      "hidden_dim": 128,
      "n_layers": 3,
      "dropout": 0.2,
      "corr_threshold": 0.1
    },
    "learning_rate": 0.001,
    "weight_decay": 0.0001,
    "batch_size": 2048,
    "epochs": 30
  },
  "training": {
    "save_dir": "D:\\Code\\hackaton_cyberpolka_CV\\models_weight\\tabnet_gnn",
    "corr_matrix_path": "D:\\Code\\hackaton_cyberpolka_CV\\artifacts\\corr_matrix_stage1.json"
  }
}